name: Apollo GitHub Projects Beta Labeler
description: Sets the project by default on new issues
author: Jesse Rosenberger
inputs:
  bearer_token:
    description: The token for communicating with the API
    required: true
  organization:
    description: The GitHub Organization login.  Defaults to current/same.

runs:
  using: 'node12'
  main: 'dist/index.js'
